### ISSUE TITLE
Setup a website

### ISSUE THREAD

**Issue by lindadelacombaz** [2DegreesInvesting/tiltPlot#11]
- To make the tiltPlot package more user-friendly, add a website to the package using `pkgdown::build_site()` and  [put in on gibhub](https://pkgdown.r-lib.org/reference/build_site_github_pages.html) 
- To evolve the package version for every new feature, use `usethis::use_version()-

**Comment by maurolepore** [comment]
@lindadelacombaz, 

I edited the title to focus this issue on the website alone. The website will reflect the changes in the NEWS.md file but the act of editing NEWS.md is not an issue in itself but rather a habit. 

Update NEWS.md after each user-facing change using this guidelines: https://style.tidyverse.org/news.html

If you want to automate the process, you may use the [fledge package](https://fledge.cynkra.com/).
