### ISSUE TITLE
Adapt Germany map to tiltIndicatorAfter

### ISSUE THREAD

**Issue by Tilmon** [2DegreesInvesting/tiltPlot#128]
Please adapt the German map to the latest version of tiltIndicatorAfter. You can find the current version of the Germany map [here](https://github.com/2DegreesInvesting/tiltPlot). 

Please reach out to @lindadelacombaz in case of questions about the visual. 

**Context:** For the webtool, we want to have two visuals: The Germany map and the bar charts. Both visuals need to be adapted to the latest version of tiltIndicatorAfter. 

cc' @AnneSchoenauer

**Comment by kalashsinghal** [comment]
Hi @AnneSchoenauer, 

Do we want the maps to show risk categories for `emission_profile`, `sector_profile`, and `transition_risk` separately? The code that Linda worte only works for the `emission_profile` risk column.

Do we also want maps for countries other than Germany as well?

**Comment by AnneSchoenauer** [comment]
Yes please :) for all three indicators would be good!

**Comment by kalashsinghal** [comment]
Hi @AnneSchoenauer , 

Unfortunately, we don't have the `equal_wight`, `best_case`, and `worst_case` calculations for sector profile at product level. Do you want me to focus on these calculations first using this ticket: https://github.com/2DegreesInvesting/tiltIndicatorAfter/issues/247 ? Or would you like me to work on creating the german map first for `emission_profile` and `transition_risk_profile` ?

FYI: Linda used the product level data to calculate the German maps.

**Comment by AnneSchoenauer** [comment]
Please focus on transition risk and emission profile first :)
