### ISSUE TITLE
Change the current toy data set to the "real toy data set", without financial data, for all the plots

### ISSUE THREAD

**Issue by lindadelacombaz** [2DegreesInvesting/tiltPlot#137]
- c.f. [Real toy data set](https://docs.google.com/spreadsheets/d/1i4a_vGXTK2Zj_7MW528tEevUeQSPlqhJHl4xGg8MAMQ/edit#gid=1438648504)
- Staggered plot and Map run well on priority

**Comment by Tilmon** [comment]
@kalashsinghal can you please review the new toy data set's column names and make sure the non-yellow ones reflect the real names from tiltIndicatorAfter? 

@Tilmon to review yellow columns' naming convention.

**Comment by Tilmon** [comment]
@AnneSchoenauer I reviewed the naming conventions and added a few comments for you (tagged your name).

**Comment by AnneSchoenauer** [comment]
Hi @Tilmon Perfect! I just had one clarification question!

**Comment by kalashsinghal** [comment]
>@kalashsinghal can you please review the new toy data set's column names and make sure the non-yellow ones reflect the real names from tiltIndicatorAfter?

@Tilmon @AnneSchoenauer I have reviewed the non-yellow column names and they are same from tiltIndicatorAfter.
