### ISSUE TITLE
Plot: Create sankey plot - PCTR

### ISSUE THREAD

**Issue by AnneSchoenauer** [2DegreesInvesting/tiltPlot#2]
Please create a sankey plot with our PCTR and ICTR data merged with credit data. I created a toy data set [here](https://docs.google.com/spreadsheets/d/1eN1J5Ew0WmLrnX7RIEt6VCz74qRdCeftPSVSpCc4jXA/edit#gid=0). 

**Background**
The dataset has loan data which are the variables `bank ` (which bank lended money to the company), the `amount` of the loan and the `probability of default`, i.e. how likely the bank thinks that the company is defaulting on the loan. Furthermore, I used the PCTR_product level data and added tilt sectors per product (`tilt_sec`). I also added how many products the company is producing (`amount_of_distinct_products`). This variable becomes important so that we can estimate how much money of the whole loan finances which products (with the assumption here that each product is equally weighted). Please note that the data in this form does not exist yet but it would be easily to get it. 

**Task Details**
The graph should now do two things: first shows how much money the banks put in different tilt sectors and then second how many products in this tilt sectors have a low, medium and high product. To get a better intuition please see [here ](https://github.com/RMI-PACTA/pacta.aggregate.loanbook.plots/blob/main/R/plot_sankey.R) a sankey plot  that I copied and pasted from PACTA's [aggregated plot.](https://github.com/RMI-PACTA/pacta.aggregate.loanbook.plots)   
![image](https://github.com/2DegreesInvesting/tiltPlot/assets/115623567/39d6dc0f-2d59-4277-b82a-95c3c76266cb)
The levels are similiar:  we have first the bank that have a certain loanbook. In the toy dataset we have three banks - a, b and c - and taking all their loans gives you their loanbook. Based on the amount of products per sector, you can then find out how much money (assuming equal weight per product) goes into specific tilt sectors

**Comment by AnneSchoenauer** [comment]
@Tilmon could you assign someone to this ticket after the PSTR/ISTR is done please?

**Comment by Tilmon** [comment]
@maurolepore let's discuss in today's sprint call who's the best to take over this task next week.

**Comment by maurolepore** [comment]
@AnneSchoenauer, do you have a link to the source of the plot? I wonder if that could lead us to the underlying code and author.

**Comment by AnneSchoenauer** [comment]
@maurolepore I thought to copied and pasted the link - please see now the updated comment above!

**Comment by maurolepore** [comment]
Thanks @AnneSchoenauer, that helps. I see 

* It's part of a package that's been developed over the past 4 months.

* It includes code to prepare then plot:
```bash
➜  pacta.aggregate.loanbook.plots git:(main) ls  R/*sankey*   
R/plot_sankey.R  R/prep_sankey.R
```

* The main developer is Monika 
```bash
➜  pacta.aggregate.loanbook.plots git:(main) git shortlog -s R/*sankey* | cat
    12  MonikaFu
     3  jacobvjk
```

* It uses `networkD3::sankeyNetwork()`, which is part of a package that CJ authors.

**Comment by AnneSchoenauer** [comment]
@Tilmon could we please have a chat next week to discuss this issue - I want to explain to you the toy data that I used for creating this sankey plot.

**Comment by maurolepore** [comment]
@AnneSchoenauer, great to know you have some toy data as we need to to develop the code. Is it public?

**Comment by AnneSchoenauer** [comment]
@maurolepore, I changed the data slightly. It is now 100% suitable for public use. Thanks!

**Comment by maurolepore** [comment]
Thanks. Would your public data work with the code you posted on #1 and #3? If so we can already add that to the package:

1. Create a new branch
2. Add the data into the directory data-raw/, e.g. data-raw/istr.csv, and data-raw/pctr.csv
3. Add the code into the directory R/, e.g. R/istr_plot.R and R/pctr_plot.R
4. Commit
5. Push
6. Create a new pull request.

**Comment by AnneSchoenauer** [comment]
Dear @maurolepore, unfortunately it doesn't. The difference is that the plots that you can see in this issue here also have toy loanbook data included, the other plots only refer to the _tilt_ database. So issue #2 uses for now different data than issue #1 and #3 . The reason is that issue #2 includes loandata and issue #1 and #3 only refer to the tilt data - the data that we also shared with the banks. However, I think we also need similiar plots as issue #1 and #3 for loan data. 

Therefore: 

1. If you work on the issue #2 (the one here) this week, are the toy_data okay for now? I created the data as such that I took the tilt data and added loanbook data. However, please note that I don't know the structure about the PACTA data. If you find in the PACTA repo the toy data with which the PACTA team was creating the sankey plot, I could also make sure that the toy data to create a tilt sankey plot has the same structure. Would that help? 
2. I will work this week on figuring out which toy data we would need for issue #1 and #3 when including the loanbook data and make sure that it looks similiar to issue #2. Would that be okay?
3. For issue #1 and issue #3 , I was using our real tilt data. The dataset is quite big and therefore, I think it wouldn't make sense to upload all for the repo. Do you want me to only extract some datapoints of our tilt data so that we could also upload the data in a repo? If so, I need to double check with Jakob, if we need to anonymise the data (as I did with the toy data for the sankey plot (issue #2).

**Comment by Tilmon** [comment]
Dear @maurolepore did you already continue with this issue? Are the toy data @AnneSchoenauer mentioned in 1. sufficient for now? I moved this ticket to tomorrow's sprint and put it on medium priority. 


> 1. If you work on the issue https://github.com/2DegreesInvesting/tiltPlot/issues/2 (the one here) this week, are the toy_data okay for now? I created the data as such that I took the tilt data and added loanbook data. However, please note that I don't know the structure about the PACTA data. If you find in the PACTA repo the toy data with which the PACTA team was creating the sankey plot, I could also make sure that the toy data to create a tilt sankey plot has the same structure. Would that help?

**Comment by maurolepore** [comment]
No @Tilmon, I did not work on this package yet. There is a lot to do in the tiltIndicator. For now I've been discussing with @AnneSchoenauer mainly to try find a relatively easy way to start. 



@AnneSchoenauer I'll re-read after some sleep but yeah, by toy data I mean only a few rows -- the fewer the better. Start easy: Identify the one simplest plot and the smallest dataset possible. Share it however you can, ideally as I suggest  [here](https://github.com/2DegreesInvesting/tiltPlot/issues/2#issuecomment-1584828974) but a .zip file is great too.

**Comment by AnneSchoenauer** [comment]
Hi everyone, alright - understood, thanks @maurolepore. I will upload the toy dataset accordingly as you suggested [here.](https://github.com/2DegreesInvesting/tiltPlot/issues/2#issuecomment-1584828974). I will do so on Friday.

**Comment by Tilmon** [comment]
Assigned to @lindadelacombaz as she is also working on [Identify and add the first plot and toy data #6](https://github.com/2DegreesInvesting/tiltPlot/issues/6) 

FYI @maurolepore

**Comment by Tilmon** [comment]
First draft from @lindadelacombaz here: [Plot: Identify and add the first plot and toy data (sankey plot of PCTR)#6](https://github.com/2DegreesInvesting/tiltPlot/issues/6)

**Comment by AnneSchoenauer** [comment]
Dear @lindadelacombaz, I reviewed your plot and thanks a lot for the first draft! Great that it in general will work! 
<img width="432" alt="image" src="https://github.com/2DegreesInvesting/tiltPlot/assets/115623567/6d0f63bf-21d0-42f4-87b5-4469309698f0">
Some comments/questions:  
- I is great that you simplified the toy data! However, I think you simplified it a bit too much. We would need a company as well . So the relationship is Bank borrows to company a certain amount. Company produces a distinct amount of products and those products are low, medium or high. PACTA also has one graph with four nodes (bank, company, sector, risk category). It should be in general possible to have the company nodes included. Maybe you could already implement this so that we have two versions of the sankey_plot? 
- I am not quite sure of how I understand the logic of your dataset. If the company only has 1 distinct product, how can it be that it is allocated to two different sectors? Talking about company A. Would be great if you could specify this! 
- I wonder why the flows are smaller from sector to risk category as they are going from A/B to sectors. Shouldn't they be exactly the same as the bars should represent exactly the same amount of money before and after the sector split?

**Comment by AnneSchoenauer** [comment]
Hi @lindadelacombaz, I did the review and if you are fine with it, happy for you to close the comment :) Good work!
