### ISSUE TITLE
Plot : Automatically save the plots in the user folder for the XCTR plot

### ISSUE THREAD

**Issue by lindadelacombaz** [2DegreesInvesting/tiltPlot#26]
- Automatically save the plots for the user for the XCTR plot for each bank found in the financial data set, in png format.
- Automatically save the plot on the portfolio level for the XCTR plot with financial data, in png format.
- Create a function like save_xctr_plot.R

This is also going to be integrated in the existing functions.

Again, @Lyanneho could help me with that :)

**Comment by AnneSchoenauer** [comment]
Hi everyone,

I understand. I think how PACTA did it, they have a workflow in which they open several R-packages, so for example the analysis or the plot packages. They then have workflow R script in which they put all the steps forward that the user needs to do with calling different fucntions, preparing different datasets etc. Here they also save the plots automatically in a created folder of the users. 

I think this saving plots would mean that we put it in a working flow script and not in the package itself. Does that make sense? If yes, we can close this comment, however make sure that in the workflow we also include to save the plots as it is super user-friendly. 

Best
Anne
