### ISSUE TITLE
Where to keep the code that prepares data for plots

### ISSUE THREAD

**Issue by AnneSchoenauer** [2DegreesInvesting/tiltPlot#29]
Dear @maurolepore, 

I am adding our slack message to this ticket to answer to your messages here in a ticket. 

@lindadelacombaz and I discussed yesterday that we would like to understand where to put certain code. To understand which code I am referring to, please re-cap our two use cases of the dataset: 

1. data —> tilt.indicator —> tilt.plot (bar charts without financial data)
2. data —> tilt.indicator —> tilt.company.match —> preparation functions —> tilt.plot (sankey plot and bar charts with financial data)

Please note that in use case 2 we give our data away after the tilt.indicator are calculated, then banks need to match it with financial data. As the financial data is highly confidential we don’t see anything thereafter (I see it as I am an employee at the Bundesbank for 6 months).

Now the question is what to do with the preparation function. They are the link between the matched data and the plots. Shall we have a different repo for this?

**Comment by AnneSchoenauer** [comment]
@maurolepore replied: 

thanks @AnneSchoenauer  for correcting the use cases I drafted above.

**Preparation code**

> Now the question is what to do with the preparation function. They are the link between the matched data and the plots. Shall we have a different repo for this?


This is the type of question which answer isn't clear-cut. And what may seem best now may change later.
As a product owner you should focus on describing the higher-level use case and as developers we should keep the code flexible so that it can adapt to changing requirements with minimum effort. Eventually users may interact with the code from top level functions
Does that preparation code already exist?
If so, where is it now?
In the early stages of development the internal architecture of a system may be fuzzy. For example, the code that prepares data may be mixed with the code that plots it. If so the split would first happen inside the tiltPlot package (e.g. moving all the data-preparation functions into different files) then maybe (or not) move to another package (e.g. moving the data preparation files to tiltPrep or wherever).
I'm allocating some time this sprint to review tiltPlot from such architectural perspective. So far I've reviewed each function in isolation but ASAP it'll help to see how they all fit together in tiltPlot and in turn how tiltPlot fits in the tilt* ecosystem.
Give banks both data and software
So what we want to do now is to actually give everything in the hand of banks
That's fine. That's the approach we used with the r2dii* packages (r2dii.match ~ tilt.company.match, r2dii.analysis ~ tiltIndicator, r2dii.plot ~ tiltPlot). The banks get the code from CRAN and they do it all themselves.
A little step forward for tilt could be to additionally create an app that allows users to interact with our software from the web-browser, but totally offline and without the need to write any code (just using the mouse). That's exactly what R Shiny does, and might be the simplest way to develop an MVP.

**Comment by AnneSchoenauer** [comment]
@maurolepore you can find some example code in the attached zip.folder that @lindadelacombaz created.

To clarify: 

@lindadelacombaz and I use this toy dataset [here](https://docs.google.com/spreadsheets/d/1i4a_vGXTK2Zj_7MW528tEevUeQSPlqhJHl4xGg8MAMQ/edit#gid=0). In the first sheet you see an extract of our indicator on product level. So this is the output that I receive once the tilt.indicator package is run and we applied some data wrangling (done by Tilman so far). 

This data is then matched to the financial data with the tilt.company.match package transforming sheet 1 to sheet 2.  This adds the column 

- `kg_id`, which is the id for a bank, 
- `amount_total`, which is the total amount of the credit that the banks grants to a company, as well as
-  `wz`, which is German and stands for "Wirtschaftszweig", which is just another name for the sector of the company. However the problem is now that we need sheet 3 that I call "financial data ready for plots" to be able to create our plots. 

The code attached is used to transform the data from sheet 2 to sheet 3. So adding the columns I-M. 

What do you think where to best put it? I also think it would be good to inlcude unit tests to this code, right? 

Priority-wise it would be great if you or Linda could work on this by the 25th of August. So nothing urgent but when I am back from holiday it would be great to have the code in a more robust form, if possible. For now I am using the pure function attached to this zip-folder. 
[Uploading weighing_loanbook (1).zip…]()


Please let me know if this is unclear!
All the best
Anne

**Comment by AnneSchoenauer** [comment]
cc'ing @bobresink

**Comment by maurolepore** [comment]
RE the workflows:

[Here](https://docs.google.com/presentation/d/1nhI1HyvFezjc7vU5z2YOwN-zV0fRn61A7icvYodPVBA/edit#slide=id.g1e5a2dcd67a_0_26) are slides that reflect the two workflows: with and without financial data.

[Clean architecture](http://bit.ly/clean-software-architecture) advises to group things that change for the same reasons and at the same time. So the code that prepares data for plots should be close to the code that actually plots the prepared data. "Close" for now means in the same package: tiltPlot.

**Comment by maurolepore** [comment]
It's hard to decide when to close this issue so I'll do it now. If anything needs to be followed up, we can open a specific issue and reference this one.
