### ISSUE TITLE
Review code for workflow Bundesbank

### ISSUE THREAD

**Issue by AnneSchoenauer** [2DegreesInvesting/tiltPlot#37]
Dear Mauro, 

Please find here a project that describes the work flow with the Bundesbank. You can see a toy data set with which you can run the two R-scripts for the financial_analysis and for the financial_visualisation. I wanted to show you how much I need to prepare the dataset to be able to do some financial_visualisations. It would also be great to see if the code that I created (with the help of Linda) is correct. 

[Workflow_with_toy_data.zip](https://github.com/2DegreesInvesting/tiltPlot/files/12515952/Workflow_with_toy_data.zip)

I would like you to do the following: 

1. Please open the R-Script_work_flow_financial_analysis and the R-Script_work_flow_financial_visualisation. It should work on your computer. (Please note I am not allowed to use any GitHub at the Bundesbank, therefore, I created a project with toy-data and send it to my 2DII Email adress, I checked it and it worked fine on my computer). 
2. Could you review the functions that I wrote and let me know if you understand what I am trying to do. If you look into the toy dataset you can see from sheet to sheet how I want to transform the data. I always checked after running the functions if the data that I created with my R-code produces the same toy data set in XLS that I created beforehand. I double checked and the code should be fine.
3. The functions should be able to work for any benchmark ((upward) emission profiles) and any scenario/year ((upwards) sector profiles). Would be great if you could create functions for any kind of them. For now they only work for the former PCTR. 
4. For the research paper we would also need plots for time_series and box_plots: I am currently working on it and would update this after I did this. 
5. I also need to prepare the dataset even one step further. To do some analysis we need a dataset with only periode and company. This is indicated in the sheet "05d_company_periode". Who do you think is best to help me with this task? I think it is quite complicated but maybe it is also only using pivot_longer? Happy to hear you thoughts on this. 
6. Could you also please think about the "bigger" infrastructure of this workflow? 

Several notes: 

1. Please note that this code is only for central banks. The difference is that for central banks you always will have many banks (bank_groups) included. That means that the whole step 5 - averaging across companies would be missing as this step averages across different banking groups. How should we handle this? Maybe we can leave it like this for now for central banks and work on functions for banks later? Shall I also create a toy dataset how a loanbook would look like for a bank? How do we best proceed?
2. Please note that there is the column "periode" included. Central banks are not required to have this column but I think most of them will also have dataset over time. I thought it is better to include it as if central banks only have one periode, it would just group according to one period. So should be fine right?
3. Please also note that unfortunately I wasn't able to run Linda's code for the sankey plots on this dataset. I don't know if I did something wrong or if there is a mistake. So would be great to have a special look at the sankey plots. I saved the outputs that I derived in the Output file in the "financial_visualiation" file so that you can have a look on this. Weirdly on my own computer they look fine... don't understand it to be honest. 
4. I also needed to manipulate Linda's code a bit so that I was able to run it on the data that I have from the central bank. I don't know if it is correctly manipulated. I also saw some mistakes in the Lindas' code, for example she averaged one time across groups, but it should be a sum. I will create tickets for this. 
5. I tried to be transparent as possible of what I want to achieve with the code. Behind this are some methodological decisions. I don't know how much you would need to understand about those methodological decisions but at any time, please let me know if there are questions!
6. There are still many to dos that I indicated within the scripts. Do you think it make sense that I still work on those or should I wait until you come up with a new infrastructure? 

Okay, this was a lot of text and maybe you want to create many tickets for this. Please also note that I am not quite sure if this would belong to the tilt.plot repo... So feel free to move this ticket, edit it with your own words. 

Please let me know if anything is unclear!

All the best
Anne

**Comment by maurolepore** [comment]
TODO

- [ ] Explore the project as described here to understand where this code fits in the tilt ecosystem.
- [ ] Outline a plan of actionable steps and discuss with Anne
- [ ] Estimate next steps, effort and milestones.

**Comment by maurolepore** [comment]
Here was the bulk of my input. I think it's best to close this issue now and follow up in focused issues wherever it's relevant. Else this issue will remain open indefinitely.
