### ISSUE TITLE
Clarify the input data for the plots without financial data

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tiltPlot#45]
> Clarify the input data for the plots, especially with regard to this issue [here](https://github.com/2DegreesInvesting/tiltIndicator/issues/474#event-9949409617). 
-- @AnneSchoenauer 

See also https://github.com/2DegreesInvesting/tiltPlot/issues/51

Note for my future self:

I opened this issue on behalf of Anne, as I turned her roadmap from a list of TODOs in a google document into a collection of issues in the "[Insights](https://github.com/2DegreesInvesting/tiltPlot/milestone/1)" milestone.

**Comment by AnneSchoenauer** [comment]
Dear @maurolepore, 

So there are three kinds of plots. Please refer to the Google Document [here](https://docs.google.com/document/d/1YA9y9HdO864X91h-ferVZw660yvMdzKWBjq7UJwy0ro/edit#heading=h.4gyjt75gfscb) again. For each of the three kinds, we need a different dataset. 

_Please note that I only refer now to the product level as the input product level still needs some enhancement. So best to focus now only on the emission profile (former PCTR) and sector profile (former PSTR)._ 

**1. Database insights which are divided into:** 
**1.1 Descriptives of database without indicators**

This would be the pre-proccessed web-scraped data (so the nlp step is done), plus all sector mapping done plus some information that comes from the raw webscaped data from ep. In my understanding, this data would be the data that is the output of the tilt indicator before part. However, to be 100% sure it would be great if you could pinpoint me to the data that you put in the "normal" tiltIndicator package.  

You can find here example data of how the data would look like. Please note that 
- in green you can see the columns that should come from the TiltIndicatorBefore package.
- in yellow you can see the columns that are included in the raw data - the one that you webscraped from ep. 
- In red you see the columns that I wanted to have included (see this issue [here](https://github.com/2DegreesInvesting/tiltIndicator/issues/473)). 


**1.2 Descriptives of database with indicators**

This would be the data that comes out of the tiltIndicatorAfter package. Again 
- in green you can see the columns that should already be included. 
- In red you see the columns that I wanted to have included (see this issue [here](https://github.com/2DegreesInvesting/tiltIndicator/issues/473)). 

This dataset is also the data that Tilman gave me for the Bundesbank. You can find this data [here](https://drive.google.com/drive/folders/1cb5mdbihj6cxncFq_vrwunuvIZEJ6lTW). 


**2. Financial insights**

This dataset is the dataset from step 1.2 plus the financial data. To make the graphs that you can see in the tiltPlot package you would need to have at least: `bank_id/bank_group`, `credit_size/amount_total`, `amount_of_distinct_products`, `equal_weight_finance`, `worst_case_finance`, `best_case_finance`.  

You can find a toy dataset that Linda used for her plots [here](https://docs.google.com/spreadsheets/d/1i4a_vGXTK2Zj_7MW528tEevUeQSPlqhJHl4xGg8MAMQ/edit#gid=574477182)



Please note: While discussing this with you, I think we could for example also think about adding the `amount of distinct products` already in the datasets after pre-processing the data. Or the `best case` and `worst case` could also already be implemented in the tiltIndicatorAfter package. But for this, lets have new tickets and this also refers to the Bundesbank workflow with regard to where to put `*analysis_R` in the ecosystem. 

I hope this helps. Please let me know if you have any questions or you cannot find the real data for each of the steps. I think if we cannot find the real data that have such columns as described here, we would need to reach out to Kalash and Yana.

**Comment by maurolepore** [comment]
I polished the title and removed a label to more accurately reflect that this issue refers to all plots without financial data -- including with and without indicators.

**Comment by maurolepore** [comment]
>  ... it would be great if you could pinpoint me to the data that you put in the "normal" tiltIndicator package.

The [example](https://2degreesinvesting.github.io/tiltIndicator/#example) at the tiltIndicator website shows `library(tiltToyData)`. If you click on "tiltToyData" you'll land at its [website](https://2degreesinvesting.github.io/tiltToyData/). That website shows a bit of every dataset, and also shows how to read any specific dataset. For example, you can read with the dataset "emissions_profile_products" with `read_csv(toy_emissions_profile_products())`.

> You can find here example data of how the data would look like.

Which dataset are you pointing me to? Did you mean to add a link behind "here"? 


> This dataset is also the data that Tilman gave me for the Bundesbank. You can find this data [here](https://drive.google.com/drive/folders/1cb5mdbihj6cxncFq_vrwunuvIZEJ6lTW).

The link behind "here" points me to a google drive with multiple files and folders. Which one do you want me to see?

**Comment by maurolepore** [comment]
@AnneSchoenauer 

Once we discuss the items in my comment above, I would consider this issue done and would close it. This would indicate that you have provided the clarifications you need necessary to re-gain this context whenever we need this information to develop specific plots.

**Comment by AnneSchoenauer** [comment]
@maurolepore 

This is fine for me! I think it becomes important for Linda and for you when you work on the plots? But happy if we close it and bring it up once it is important again!

**Comment by maurolepore** [comment]
OK. But before I close it note that I have two questions [above](https://github.com/2DegreesInvesting/tiltPlot/issues/45#issuecomment-1713860055).

**Comment by AnneSchoenauer** [comment]
Hi Mauro, 

Please find my answers below: 

> The [example](https://2degreesinvesting.github.io/tiltIndicator/#example) at the tiltIndicator website shows library(tiltToyData). If you click on "tiltToyData" you'll land at its [website](https://2degreesinvesting.github.io/tiltToyData/). That website shows a bit of every dataset, and also shows how to read any specific dataset. For example, you can read with the dataset "emissions_profile_products" with read_csv(toy_emissions_profile_products()).

Thanks a lot for this. This makes a lot of sense and I understand better. I also pinpointed Bob to it again. I thought that Bob, Tilman and Kalash reviewed it but I make also sure to run the whole package next week to see if I find any mistakes in the methodology, data etc. 

> Which dataset are you pointing me to? Did you mean to add a link behind "here"?

Embarassing! The whole ticket was about creating some sample data (I was in the train when I wrote the ticket so most likely it didn't upload or I forgot about it). Anyhow, I now linked the sample data above. 

> The link behind "here" points me to a google drive with multiple files and folders. Which one do you want me to see?

Yes that is right as all of the data are the same data just for different jurisdiction. I would suggest that you would look at the folder `ALL_countries`, which is [here](https://drive.google.com/drive/folders/1UNOaVhj-_v2OgIVTd-1rTUT-ayorX3_h). You then can find two datasets per indicator - one on the company level and one on the product level. I always used the product level when I created the plots. So I would suggest that you start looking at the `pctr_product_level.zip`. This is the data for the emission profile. 

Please note for context - the files that you can see in the folder [here ](https://drive.google.com/drive/folders/1cb5mdbihj6cxncFq_vrwunuvIZEJ6lTW)are the data that we shared with the banks. The reason why we didn't share with them the tiltIndicator Package yet is that you need as input data raw data from ecoinvent. However, the banks don't have licenses with ecoinvent yet. Therefore, we calculated the data for them and send them the output file after the tiltIndicator package. For the future we however would like to have a process in which all banks have their own license and can calculate the indicators themselves. Hope this helps for an understanding.

**Comment by maurolepore** [comment]
Thanks @AnneSchoenauer and cc' @lindadelacombaz 

For emissions profile at product level, it's now clear that we the output of tiltIndicator does connect to the input of tiltPlot. Here is a reprex showing the connection from end-to-end.

``` r
library(tiltToyData)
library(tiltIndicator)
library(tiltPlot)
library(dplyr, warn.conflicts = FALSE)
library(readr, warn.conflicts = FALSE)

options(readr.show_col_types = FALSE)

companies <- read_csv(toy_emissions_profile_any_companies())
products <- read_csv(toy_emissions_profile_products())

emissions_profile <- emissions_profile(companies, products)
at_product_level <- unnest_product(emissions_profile)

# Adapt the ouput of tiltIindicator to the input of tiltPlot
all_companies <- at_product_level |> 
  rename(xctr_risk_category = risk_category, benchmark = grouped_by)

plot_xctr(all_companies)
```

![](https://i.imgur.com/5DbkXqV.png)

This also shows that tiltPlot does not need new toy datasets -- the toy datasets in tiltToyData are enough. 

At this early stage of development I think the "beautification" of column names is a bad idea and instead we should prefer consistency. The tiltIndicator package outputs ugly names but the are consistent across all indicators. If we stick to those ugly names, we can feed the output of tiltIndicator directly into tiltPlot. In any case if we build an interactive tool on top of our packages, the ugly names will remain hidden in the back-end and the users would only see more polished output in the front-end. If we go that way we may not need tiltIndicatorAfter -- at least not for now.

**Comment by maurolepore** [comment]
As this is now clear to me, I'll go ahead and close this issue. Thanks @AnneSchoenauer.
