### ISSUE TITLE
Change heading of XCTR plots without financial data

### ISSUE THREAD

**Issue by AnneSchoenauer** [2DegreesInvesting/tiltPlot#62]
Dear Linda, 
Could you please change the heading from the `XCTR plots without financial data` from "Risk distribution of..." to "Relative emission profile of all products...". 
Thanks a lot!
Best
Anne

**Comment by maurolepore** [comment]
@lindadelacombaz, at this early stage of development I think it's best for tiltPlot to not include headings in the code of the package but rather to show examples of how to use `ggplot2` to do that. The cost of maintainance for such a brittle detail is too high.
