### ISSUE TITLE
Create and define objectives and requirements for the RShiny App

### ISSUE THREAD

**Issue by AnneSchoenauer** [2DegreesInvesting/tiltPlot#76]
I will follow the suggestions from Chat GPT to define and clarify the objectives and requirements for the RShiny App.  @maurolepore  FYI you can find the chat [here](https://chat.openai.com/share/d4788cf1-b55e-4091-8112-90e76c0c49de). Let me know if you have concerns otherwise I will follow up with a document defining the first point - objectives and requirements for the RShiny App.

**Comment by maurolepore** [comment]
The chat looks good Anne and I appreciate your effort. As I already have quite some context, you may skip many of the items I see on the chat.
