### ISSUE TITLE
Change license to GPLv3

### ISSUE THREAD

**Issue by maurolepore** [2DegreesInvesting/tiltPlot#77]
Relates to [2DegreesInvesting//TiltDevProjectMGMT#148
](https://github.com/2DegreesInvesting/TiltDevProjectMGMT/issues/148)

https://r-pkgs.org/license.html#relicensing
> Ask every contributor if they’re OK with changing the license. If every contributor is on GitHub, the easiest way to do this is to create an issue where you list all contributors and ask them to confirm that they’re OK with the change.

Based on DESCRIPTION and `git shortlog -s` you are all contributors to this package:

- [x] @lindadelacombaz 
- [x] @AnneSchoenauer 
- [x] @maurolepore 

Do you agree with the change?

If you agree please write a comment saying "Yes".

**Comment by AnneSchoenauer** [comment]
Yes.
