### ISSUE TITLE
New plot: Create new scatter plot

### ISSUE THREAD

**Issue by AnneSchoenauer** [2DegreesInvesting/tiltPlot#85]
@Tilmon and I came up with a new scatter plot. The scatter plot should look like this: 

![Image](https://github.com/2DegreesInvesting/tiltIndicator/assets/115623567/c4b8dd7f-27c1-41a3-a7ff-163284ea520f)

Please note that this work depends on the transition risk score. That's why it will be something for next week.

**Comment by Tilmon** [comment]
@lindadelacombaz few more infos regarding this task: 

- emission rank is data from the emission_profile
- transition risk score is the average of emission rank and sector reduction target and can be taken from tiltIndicatorAfter
- The Y axis should show values between 0 and 1
- The X axis shows exposure between 0 and 1, as % of `amount_total `per sector

What you need to add to the existing data is: 
- financial toy data to tiltIndicatorAfter , incl. `amount_total `
