### ISSUE TITLE
Make nice headings for Map and Staggered plot, without financial data

### ISSUE THREAD

**Issue by AnneSchoenauer** [2DegreesInvesting/tiltPlot#88]

**Comment by AnneSchoenauer** [comment]
Hi Linda - let's sit down together and create good headings for each of the plots. Once everything is pushed I will go through the plots and come up with good headings! Thanks a lot. Best Anne

**Comment by lindadelacombaz** [comment]
@AnneSchoenauer, this it the ticket to make the nice **headings and x, y labels** for the plots, namely:
1. Map without financial data for the transition, sector and emission profile
2. Bar charts without financial data, for the transition, sector and emission profile

**Comment by AnneSchoenauer** [comment]
This is a suggestion and needs to be validated and reviewed by @Tilmon before we implement it!

For the bar plot for single companies
<img width="329" alt="image" src="https://github.com/2DegreesInvesting/tiltPlot/assets/115623567/8b0f75c1-528c-4265-856f-9fc7f8c76572">

Heading: "Emission Profile / Sector Profile / Transition Risk Score" for all products of company [name of the company] with the "equal weight/ best case /worst case" assumption
x-Axis: "grouping categories"
y-Axis: Percentage share in (%)
Legend: "Emission Profile/ Sector Profile / Transition Risk Score", green = low, yellow = medium, red = high

<img width="328" alt="image" src="https://github.com/2DegreesInvesting/tiltPlot/assets/115623567/00e9831e-cf9c-46b6-889e-304029ede689">
Heading: "Emission Profile / Sector Profile / Transition Risk Score" for all products on portfolio level with the "equal weight/ best case /worst case" assumption
x-Axis: "grouping categories"
y-Axis: Percentage share in (%)
Legend: "Emission Profile/ Sector Profile / Transition Risk Score", green = low, yellow = medium, red = high

<img width="329" alt="image" src="https://github.com/2DegreesInvesting/tiltPlot/assets/115623567/ef4127ef-8afa-488a-aa10-3549f918a995">
Heading: "Emission Profile / Sector Profile / Transition Risk Score" per region with the "equal weight/ best case /worst case" assumption
Legend: ? @lindadelacombaz could you show me the legends here first so that I know how to call them?

**Comment by lindadelacombaz** [comment]
@AnneSchoenauer, yes the legend here is 
"German map of high, medium and low proportions of the companies that are found in one region.
© EuroGeographics for the administrative boundaries"

**Comment by AnneSchoenauer** [comment]
@lindadelacombaz I mean what does red, yellow and green mean - and if I recall correctly we have also mixed colours possible correct?

**Comment by lindadelacombaz** [comment]
@AnneSchoenauer yes, exactly. The panel goes from green to red, will different the in-between colors possible (depends on the proportion of the companies that are found in the region that are categorized as high, medium or low.)

**Comment by Tilmon** [comment]
Dear @AnneSchoenauer and @lindadelacombaz, re

> This is a suggestion and needs to be validated and reviewed by @Tilmon before we implement it!

Title suggestions sound great! Two small comments: 

1. You confused x- and y-axis I think. I.e., Y-Axis should be "grouping categories" and X-Axis "Percentage share..."
2. X-Axis "Percentage share in %" is not completely adequate because right now the X-Axis values are 0-1, not 0-100, i.e. it's not in % but expressed as decimal already. Hence, I'd either say sth like "Share of low/medium/high" or change the values on X-axis to 0-100 so that they actually express %-values. 

Hope that helps!
