### ISSUE TITLE
Explore / Fix issues with dependencies in TiltPlot package that makes checks() to fail.

### ISSUE THREAD

**Issue by lindadelacombaz** [2DegreesInvesting/tiltPlot#89]
Dear @maurolepore,
I am assigning the ticket to you that I have had initially created for @kalashsinghal.

I have encountered an issue when I was working on a ticket: in my local Rstudio every checks() passes, but when I create a PR on GitHub, every checks() fails (see my [PR 89](https://github.com/2DegreesInvesting/tiltPlot/pull/83)). I have installed the latest tiltIndicator and tiltToyData packages following their README instructions.
Talking with you about it, it seems related to some dependencies on other packages (probably tiltIndicator and tiltToyData).

Here is the [related PR](https://github.com/2DegreesInvesting/tiltPlot/pull/79) that you have created in tiltPlot for that issue.

Thank you ! :))

**Comment by maurolepore** [comment]
@lindadelacombaz see:

- [ ]  https://github.com/2DegreesInvesting/tiltPlot/pull/79
- [ ] https://github.com/2DegreesInvesting/tiltPlot/issues/91
